// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CharacterDbContext))]
    partial class CharacterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackgroundFeat", b =>
                {
                    b.Property<int>("BackgroundId")
                        .HasColumnType("int");

                    b.Property<int>("FeatsId")
                        .HasColumnType("int");

                    b.HasKey("BackgroundId", "FeatsId");

                    b.HasIndex("FeatsId");

                    b.ToTable("BackgroundFeats", (string)null);
                });

            modelBuilder.Entity("BackgroundFeature", b =>
                {
                    b.Property<int>("BackgroundId")
                        .HasColumnType("int");

                    b.Property<int>("FeaturesId")
                        .HasColumnType("int");

                    b.HasKey("BackgroundId", "FeaturesId");

                    b.HasIndex("FeaturesId");

                    b.ToTable("BackgroundFeatures", (string)null);
                });

            modelBuilder.Entity("BackgroundGrantedProficiency", b =>
                {
                    b.Property<int>("BackgroundId")
                        .HasColumnType("int");

                    b.Property<int>("ProficienciesId")
                        .HasColumnType("int");

                    b.HasKey("BackgroundId", "ProficienciesId");

                    b.HasIndex("ProficienciesId");

                    b.ToTable("BackgroundProficiencies", (string)null);
                });

            modelBuilder.Entity("Core.Entities.ASI.Feat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feats");
                });

            modelBuilder.Entity("Core.Entities.Advancement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvancementType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Advancements");

                    b.HasDiscriminator<string>("AdvancementType").HasValue("Advancement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.Background", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Backgrounds");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("BackgroundId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("int");

                    b.Property<string>("ImageFrame")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NegativeHp")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("TempHp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("RaceId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterAbilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterAbilities");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterConditions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Blinded")
                        .HasColumnType("bit");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool>("Charmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Deafened")
                        .HasColumnType("bit");

                    b.Property<int>("Exhausted")
                        .HasColumnType("int");

                    b.Property<bool>("Frightened")
                        .HasColumnType("bit");

                    b.Property<bool>("Grappled")
                        .HasColumnType("bit");

                    b.Property<bool>("Incapacitated")
                        .HasColumnType("bit");

                    b.Property<bool>("Invisible")
                        .HasColumnType("bit");

                    b.Property<bool>("Paralyzed")
                        .HasColumnType("bit");

                    b.Property<bool>("Petrified")
                        .HasColumnType("bit");

                    b.Property<bool>("Poisoned")
                        .HasColumnType("bit");

                    b.Property<bool>("Prone")
                        .HasColumnType("bit");

                    b.Property<bool>("Restrained")
                        .HasColumnType("bit");

                    b.Property<bool>("Stunned")
                        .HasColumnType("bit");

                    b.Property<bool>("Unconscious")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterConditions");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterFeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("FeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeatId");

                    b.HasIndex("CharacterId", "FeatId")
                        .IsUnique();

                    b.ToTable("CharacterFeats", (string)null);
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterFeature", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<int?>("RemainingUses")
                        .HasColumnType("int");

                    b.Property<int?>("RestType")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<bool?>("UsesSpellSlots")
                        .HasColumnType("bit");

                    b.HasKey("CharacterId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("CharacterFeatures", (string)null);
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterPhysicalCharacteristics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Eyes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Hair")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Skin")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterPhysicalCharacteristics", (string)null);
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterPreparedSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SpellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.HasIndex("SpellId");

                    b.HasIndex("CharacterId", "SpellId", "CharacterClassId")
                        .IsUnique();

                    b.ToTable("CharacterPreparedSpells", (string)null);
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("GrantedProficiencyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrantedProficiencyId");

                    b.HasIndex("CharacterId", "GrantedProficiencyId")
                        .IsUnique();

                    b.ToTable("CharacterProficiencies", (string)null);
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterSpellSlots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("MaxLevel1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxLevel2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxLevel3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxLevel4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxLevel5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxLevel6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxLevel7")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxLevel8")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxLevel9")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UsedLevel1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UsedLevel2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UsedLevel3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UsedLevel4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UsedLevel5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UsedLevel6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UsedLevel7")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UsedLevel8")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UsedLevel9")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterSpellSlots");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HitDice")
                        .HasColumnType("int");

                    b.Property<bool>("IsSpellcaster")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CharacterClasses");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterClassFeature", b =>
                {
                    b.Property<int>("CharacterClassId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("CharacterClassId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("CharacterClassFeature");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterClassMulticlassProficiency", b =>
                {
                    b.Property<int>("CharacterClassId")
                        .HasColumnType("int");

                    b.Property<int>("GrantedProficiencyId")
                        .HasColumnType("int");

                    b.HasKey("CharacterClassId", "GrantedProficiencyId");

                    b.HasIndex("GrantedProficiencyId");

                    b.ToTable("CharacterClassMulticlassProficiency");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterClassPrimaryProficiency", b =>
                {
                    b.Property<int>("CharacterClassId")
                        .HasColumnType("int");

                    b.Property<int>("GrantedProficiencyId")
                        .HasColumnType("int");

                    b.HasKey("CharacterClassId", "GrantedProficiencyId");

                    b.HasIndex("GrantedProficiencyId");

                    b.ToTable("CharacterClassPrimaryProficiency");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterSubclass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSpellcaster")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("CharacterSubclasses");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterSubclassFeature", b =>
                {
                    b.Property<int>("CharacterSubclassId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("CharacterSubclassId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("CharacterSubclassFeature");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterSubclassProficiency", b =>
                {
                    b.Property<int>("CharacterSubclassId")
                        .HasColumnType("int");

                    b.Property<int>("GrantedProficiencyId")
                        .HasColumnType("int");

                    b.HasKey("CharacterSubclassId", "GrantedProficiencyId");

                    b.HasIndex("GrantedProficiencyId");

                    b.ToTable("CharacterSubclassProficiency");
                });

            modelBuilder.Entity("Core.Entities.Classes.ClassAdvancement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("EntryType")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassAdvancements");
                });

            modelBuilder.Entity("Core.Entities.Classes.SubclassAdvancement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("SubclassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SubclassId");

                    b.ToTable("SubclassAdvancements");
                });

            modelBuilder.Entity("Core.Entities.Dictionaries.Dictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Dictionaries");
                });

            modelBuilder.Entity("Core.Entities.Dictionaries.DictionaryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DictionaryCategories");
                });

            modelBuilder.Entity("Core.Entities.Dictionaries.DictionaryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DictionaryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId");

                    b.ToTable("DictionaryItems");
                });

            modelBuilder.Entity("Core.Entities.Features.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeatureKind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Core.Entities.GrantedProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProficiencyCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ProficiencyId")
                        .HasColumnType("int");

                    b.Property<int?>("ProficiencyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProficiencyCategoryId");

                    b.HasIndex("ProficiencyId");

                    b.HasIndex("ProficiencyTypeId");

                    b.ToTable("GrantedProficiencies", t =>
                        {
                            t.HasCheckConstraint("CK_GrantedProficiency_ExactlyOneTarget", "(ProficiencyId IS NOT NULL AND ProficiencyTypeId IS NULL) OR (ProficiencyId IS NULL AND ProficiencyTypeId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Core.Entities.Prerequisites.Prerequisite", b =>
                {
                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Operator")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OwnerType", "OwnerId", "GroupId", "Type");

                    b.HasIndex("OwnerId");

                    b.ToTable("Prerequisites");
                });

            modelBuilder.Entity("Core.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Core.Entities.Spells.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConcentration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDuration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRitual")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Core.Entities.Spells.Spellbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Spellbooks");
                });

            modelBuilder.Entity("Core.Entities.Spells.SpellbookSpell", b =>
                {
                    b.Property<int>("SpellId")
                        .HasColumnType("int");

                    b.Property<int>("SpellbookId")
                        .HasColumnType("int");

                    b.HasKey("SpellId", "SpellbookId");

                    b.HasIndex("SpellbookId");

                    b.ToTable("SpellbookSpells");
                });

            modelBuilder.Entity("FeatRace", b =>
                {
                    b.Property<int>("FeatsId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("FeatsId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceFeats", (string)null);
                });

            modelBuilder.Entity("FeatureRace", b =>
                {
                    b.Property<int>("FeaturesId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("FeaturesId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceFeatures", (string)null);
                });

            modelBuilder.Entity("GrantedProficiencyRace", b =>
                {
                    b.Property<int>("ProficienciesId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("ProficienciesId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceProficiencies", (string)null);
                });

            modelBuilder.Entity("RaceSpell", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("SpellsId")
                        .HasColumnType("int");

                    b.HasKey("RaceId", "SpellsId");

                    b.HasIndex("SpellsId");

                    b.ToTable("RaceSpells", (string)null);
                });

            modelBuilder.Entity("Core.Entities.ASI.AbilityScoreImprovement", b =>
                {
                    b.HasBaseType("Core.Entities.Advancement");

                    b.Property<int?>("CharacterId1")
                        .HasColumnType("int");

                    b.HasIndex("CharacterId1");

                    b.ToTable("Advancements", t =>
                        {
                            t.Property("CharacterId1")
                                .HasColumnName("AbilityScoreImprovement_CharacterId1");
                        });

                    b.HasDiscriminator().HasValue("ASI");
                });

            modelBuilder.Entity("Core.Entities.ASI.FeatAdvancement", b =>
                {
                    b.HasBaseType("Core.Entities.Advancement");

                    b.Property<int?>("CharacterId1")
                        .HasColumnType("int");

                    b.Property<int?>("FeatId")
                        .HasColumnType("int");

                    b.HasIndex("CharacterId1");

                    b.HasIndex("FeatId");

                    b.HasDiscriminator().HasValue("Feat");
                });

            modelBuilder.Entity("BackgroundFeat", b =>
                {
                    b.HasOne("Core.Entities.Background", null)
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.ASI.Feat", null)
                        .WithMany()
                        .HasForeignKey("FeatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackgroundFeature", b =>
                {
                    b.HasOne("Core.Entities.Background", null)
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Features.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackgroundGrantedProficiency", b =>
                {
                    b.HasOne("Core.Entities.Background", null)
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.GrantedProficiency", null)
                        .WithMany()
                        .HasForeignKey("ProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.ASI.Feat", b =>
                {
                    b.OwnsMany("Core.Entities.ASI.AbilityScoreBonus", "AbilityBonuses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Ability")
                                .HasColumnType("int");

                            b1.Property<int>("Amount")
                                .HasColumnType("int");

                            b1.Property<int>("FeatId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("FeatId");

                            b1.ToTable("FeatAbilityBonuses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FeatId");
                        });

                    b.Navigation("AbilityBonuses");
                });

            modelBuilder.Entity("Core.Entities.Advancement", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", "Character")
                        .WithMany("Advancements")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.Character", b =>
                {
                    b.HasOne("Core.Entities.Background", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterAbilities", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", "Character")
                        .WithOne("CharacterAbilities")
                        .HasForeignKey("Core.Entities.CharacterEntities.CharacterAbilities", "CharacterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterConditions", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", "Character")
                        .WithOne("CharacterConditions")
                        .HasForeignKey("Core.Entities.CharacterEntities.CharacterConditions", "CharacterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterFeat", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", null)
                        .WithMany("Feats")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.ASI.Feat", "Feat")
                        .WithMany()
                        .HasForeignKey("FeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feat");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterFeature", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", null)
                        .WithMany("Features")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Features.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterPhysicalCharacteristics", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", "Character")
                        .WithOne("PhysicalCharacteristics")
                        .HasForeignKey("Core.Entities.CharacterEntities.CharacterPhysicalCharacteristics", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterPreparedSpell", b =>
                {
                    b.HasOne("Core.Entities.Classes.CharacterClass", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.CharacterEntities.Character", "Character")
                        .WithMany("CharacterPreparedSpells")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Spells.Spell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("CharacterClass");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterProficiency", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", null)
                        .WithMany("Proficiencies")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.GrantedProficiency", "GrantedProficiency")
                        .WithMany()
                        .HasForeignKey("GrantedProficiencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrantedProficiency");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.CharacterSpellSlots", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", null)
                        .WithOne("CharacterSpellSlots")
                        .HasForeignKey("Core.Entities.CharacterEntities.CharacterSpellSlots", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterClassFeature", b =>
                {
                    b.HasOne("Core.Entities.Classes.CharacterClass", "CharacterClass")
                        .WithMany("Features")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Features.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterClassMulticlassProficiency", b =>
                {
                    b.HasOne("Core.Entities.Classes.CharacterClass", "CharacterClass")
                        .WithMany("MulticlassProficiencies")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.GrantedProficiency", "GrantedProficiency")
                        .WithMany("ClassMulticlassProficiencies")
                        .HasForeignKey("GrantedProficiencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");

                    b.Navigation("GrantedProficiency");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterClassPrimaryProficiency", b =>
                {
                    b.HasOne("Core.Entities.Classes.CharacterClass", "CharacterClass")
                        .WithMany("PrimaryProficiencies")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.GrantedProficiency", "GrantedProficiency")
                        .WithMany("ClassPrimaryProficiencies")
                        .HasForeignKey("GrantedProficiencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");

                    b.Navigation("GrantedProficiency");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterSubclass", b =>
                {
                    b.HasOne("Core.Entities.Classes.CharacterClass", "Class")
                        .WithMany("Subclasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterSubclassFeature", b =>
                {
                    b.HasOne("Core.Entities.Classes.CharacterSubclass", "CharacterSubclass")
                        .WithMany("Features")
                        .HasForeignKey("CharacterSubclassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Features.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSubclass");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterSubclassProficiency", b =>
                {
                    b.HasOne("Core.Entities.Classes.CharacterSubclass", "CharacterSubclass")
                        .WithMany("Proficiencies")
                        .HasForeignKey("CharacterSubclassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.GrantedProficiency", "GrantedProficiency")
                        .WithMany("SubclassProficiencies")
                        .HasForeignKey("GrantedProficiencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSubclass");

                    b.Navigation("GrantedProficiency");
                });

            modelBuilder.Entity("Core.Entities.Classes.ClassAdvancement", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", "Character")
                        .WithMany("ClassAdvancements")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Classes.CharacterClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Character");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Core.Entities.Classes.SubclassAdvancement", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", "Character")
                        .WithMany("SubclassAdvancements")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Classes.CharacterSubclass", "Subclass")
                        .WithMany()
                        .HasForeignKey("SubclassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Character");

                    b.Navigation("Subclass");
                });

            modelBuilder.Entity("Core.Entities.Dictionaries.Dictionary", b =>
                {
                    b.HasOne("Core.Entities.Dictionaries.DictionaryCategory", "Category")
                        .WithMany("Dictionaries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Entities.Dictionaries.DictionaryItem", b =>
                {
                    b.HasOne("Core.Entities.Dictionaries.Dictionary", "Dictionary")
                        .WithMany("Items")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("Core.Entities.Features.Feature", b =>
                {
                    b.HasOne("Core.Entities.Spells.Spell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellId");

                    b.OwnsMany("Core.Entities.ASI.AbilityScoreBonus", "AbilityBonuses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Ability")
                                .HasColumnType("int");

                            b1.Property<int>("Amount")
                                .HasColumnType("int");

                            b1.Property<int>("FeatureId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("FeatureId");

                            b1.ToTable("FeatureAbilityBonuses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FeatureId");
                        });

                    b.Navigation("AbilityBonuses");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Core.Entities.GrantedProficiency", b =>
                {
                    b.HasOne("Core.Entities.Dictionaries.DictionaryCategory", "ProficiencyCategory")
                        .WithMany()
                        .HasForeignKey("ProficiencyCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Core.Entities.Dictionaries.DictionaryItem", "Proficiency")
                        .WithMany()
                        .HasForeignKey("ProficiencyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Core.Entities.Dictionaries.Dictionary", "ProficiencyType")
                        .WithMany()
                        .HasForeignKey("ProficiencyTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Proficiency");

                    b.Navigation("ProficiencyCategory");

                    b.Navigation("ProficiencyType");
                });

            modelBuilder.Entity("Core.Entities.Prerequisites.Prerequisite", b =>
                {
                    b.HasOne("Core.Entities.ASI.Feat", null)
                        .WithMany("Prerequisites")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK_Feat_Prerequisites_OwnerId");

                    b.HasOne("Core.Entities.Features.Feature", null)
                        .WithMany("Prerequisites")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK_Feature_Prerequisites_OwnerId");
                });

            modelBuilder.Entity("Core.Entities.Spells.SpellbookSpell", b =>
                {
                    b.HasOne("Core.Entities.Spells.Spell", "Spell")
                        .WithMany("SpellbookSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Spells.Spellbook", "Spellbook")
                        .WithMany("SpellbookSpells")
                        .HasForeignKey("SpellbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spell");

                    b.Navigation("Spellbook");
                });

            modelBuilder.Entity("FeatRace", b =>
                {
                    b.HasOne("Core.Entities.ASI.Feat", null)
                        .WithMany()
                        .HasForeignKey("FeatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeatureRace", b =>
                {
                    b.HasOne("Core.Entities.Features.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrantedProficiencyRace", b =>
                {
                    b.HasOne("Core.Entities.GrantedProficiency", null)
                        .WithMany()
                        .HasForeignKey("ProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaceSpell", b =>
                {
                    b.HasOne("Core.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Spells.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.ASI.AbilityScoreImprovement", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", null)
                        .WithMany("ASIAdvancements")
                        .HasForeignKey("CharacterId1");

                    b.OwnsMany("Core.Entities.ASI.AbilityScoreBonus", "AbilityBonuses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Ability")
                                .HasColumnType("int");

                            b1.Property<int>("AbilityScoreImprovementId")
                                .HasColumnType("int");

                            b1.Property<int>("Amount")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("AbilityScoreImprovementId");

                            b1.ToTable("ASIAbilityBonuses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AbilityScoreImprovementId");
                        });

                    b.Navigation("AbilityBonuses");
                });

            modelBuilder.Entity("Core.Entities.ASI.FeatAdvancement", b =>
                {
                    b.HasOne("Core.Entities.CharacterEntities.Character", null)
                        .WithMany("FeatAdvancements")
                        .HasForeignKey("CharacterId1");

                    b.HasOne("Core.Entities.ASI.Feat", "Feat")
                        .WithMany()
                        .HasForeignKey("FeatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Feat");
                });

            modelBuilder.Entity("Core.Entities.ASI.Feat", b =>
                {
                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("Core.Entities.CharacterEntities.Character", b =>
                {
                    b.Navigation("ASIAdvancements");

                    b.Navigation("Advancements");

                    b.Navigation("CharacterAbilities")
                        .IsRequired();

                    b.Navigation("CharacterConditions")
                        .IsRequired();

                    b.Navigation("CharacterPreparedSpells");

                    b.Navigation("CharacterSpellSlots");

                    b.Navigation("ClassAdvancements");

                    b.Navigation("FeatAdvancements");

                    b.Navigation("Feats");

                    b.Navigation("Features");

                    b.Navigation("PhysicalCharacteristics")
                        .IsRequired();

                    b.Navigation("Proficiencies");

                    b.Navigation("SubclassAdvancements");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterClass", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("MulticlassProficiencies");

                    b.Navigation("PrimaryProficiencies");

                    b.Navigation("Subclasses");
                });

            modelBuilder.Entity("Core.Entities.Classes.CharacterSubclass", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Proficiencies");
                });

            modelBuilder.Entity("Core.Entities.Dictionaries.Dictionary", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Core.Entities.Dictionaries.DictionaryCategory", b =>
                {
                    b.Navigation("Dictionaries");
                });

            modelBuilder.Entity("Core.Entities.Features.Feature", b =>
                {
                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("Core.Entities.GrantedProficiency", b =>
                {
                    b.Navigation("ClassMulticlassProficiencies");

                    b.Navigation("ClassPrimaryProficiencies");

                    b.Navigation("SubclassProficiencies");
                });

            modelBuilder.Entity("Core.Entities.Spells.Spell", b =>
                {
                    b.Navigation("SpellbookSpells");
                });

            modelBuilder.Entity("Core.Entities.Spells.Spellbook", b =>
                {
                    b.Navigation("SpellbookSpells");
                });
#pragma warning restore 612, 618
        }
    }
}
